//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPMIntegration
{
    using System;
    using System.Collections.Generic;
    
    public partial class api_log_request
    {
        public long id { get; set; }
        public string request_direction { get; set; }
        public string request_url { get; set; }
        public string request_method { get; set; }
        public string request_header { get; set; }
        public string request_body { get; set; }
        public string response_body { get; set; }
        public string response_error { get; set; }
        public Nullable<int> app_id { get; set; }
        public Nullable<decimal> time_load { get; set; }
        public string user_id { get; set; }
        public System.DateTime create_date { get; set; }
        public string ip_address { get; set; }
    }
}
