//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPMIntegration
{
    using System;
    using System.Collections.Generic;
    
    public partial class api_url
    {
        public int url_id { get; set; }
        public string url_value { get; set; }
        public string url_method { get; set; }
        public string url_name { get; set; }
        public string url_desc { get; set; }
        public string group_code { get; set; }
        public Nullable<int> exec_order { get; set; }
        public string create_id { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string modify_id { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public string file_template { get; set; }
    }
}
