//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPMIntegration
{
    using System;
    using System.Collections.Generic;
    
    public partial class api_client_configuration
    {
        public int api_id { get; set; }
        public string api_name { get; set; }
        public string api_desc { get; set; }
        public string env_name { get; set; }
        public string client_desc { get; set; }
        public string api_key { get; set; }
        public string access_token { get; set; }
        public string host_name { get; set; }
        public string port { get; set; }
        public string http_method { get; set; }
        public string url { get; set; }
        public string content_type { get; set; }
        public string authentication_name { get; set; }
        public System.DateTime create_date { get; set; }
        public string create_id { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public string modify_id { get; set; }
        public string status { get; set; }
    }
}
