//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPMIntegration
{
    using System;
    using System.Collections.Generic;
    
    public partial class api_parameter
    {
        public string parameter_code { get; set; }
        public string parameter_desc { get; set; }
        public string userid { get; set; }
        public string password { get; set; }
        public string sender { get; set; }
        public string division { get; set; }
        public string batchname { get; set; }
        public string channel { get; set; }
        public string prefixcode { get; set; }
    }
}
