//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPMIntegration
{
    using System;
    using System.Collections.Generic;
    
    public partial class api_application
    {
        public int app_id { get; set; }
        public string app_token { get; set; }
        public string app_desc { get; set; }
        public string grant_type { get; set; }
        public string url_access { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string client_secret { get; set; }
        public string scope { get; set; }
        public string client_auth { get; set; }
        public string st_active { get; set; }
        public System.DateTime create_date { get; set; }
        public string create_id { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public string modify_id { get; set; }
    }
}
