//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPMIntegration
{
    using System;
    using System.Collections.Generic;
    
    public partial class it_report_list
    {
        public int code { get; set; }
        public string descr { get; set; }
        public string url { get; set; }
        public string folder { get; set; }
        public string report_name { get; set; }
        public Nullable<int> share { get; set; }
    }
}
