//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPMIntegration
{
    using System;
    using System.Collections.Generic;
    
    public partial class it_task_register
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public it_task_register()
        {
            this.it_task_schedule = new HashSet<it_task_schedule>();
        }
    
        public string task_code { get; set; }
        public string task_name { get; set; }
        public string task_desc { get; set; }
        public string group_status { get; set; }
        public string task_type { get; set; }
        public string task_object { get; set; }
        public string group_code { get; set; }
        public Nullable<int> exec_order { get; set; }
        public string create_id { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string modify_id { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public string file_template { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<it_task_schedule> it_task_schedule { get; set; }
    }
}
