//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPMIntegration
{
    using System;
    using System.Collections.Generic;
    
    public partial class it_task_schedule
    {
        public int register_id { get; set; }
        public string task_code { get; set; }
        public string desc { get; set; }
        public string schedule_type { get; set; }
        public Nullable<System.DateTime> start_schedule { get; set; }
        public Nullable<System.DateTime> next_schedule { get; set; }
        public int interval { get; set; }
        public string interval_unit { get; set; }
        public string ref_id { get; set; }
        public string status { get; set; }
        public string stage { get; set; }
        public string output_type { get; set; }
        public string create_id { get; set; }
        public System.DateTime create_date { get; set; }
        public string modify_id { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public string bps_id { get; set; }
    
        public virtual it_task_register it_task_register { get; set; }
    }
}
