//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPMIntegration
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_participant_list_history
    {
        public long rowid { get; set; }
        public string regno { get; set; }
        public string batch_id { get; set; }
        public int participant_status { get; set; }
        public int notif_status { get; set; }
        public string id { get; set; }
        public string clientRefId { get; set; }
        public string clientCompany { get; set; }
        public string lenderBranchCode { get; set; }
        public string lenderBranchLabel { get; set; }
        public string idNumber { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> dateOfBirth { get; set; }
        public string gender { get; set; }
        public string address { get; set; }
        public string maritalStatus { get; set; }
        public string fundManagementType { get; set; }
        public string debtorId { get; set; }
        public string loanId { get; set; }
        public string lenderProductCode { get; set; }
        public string lenderProductType { get; set; }
        public Nullable<decimal> ceilingAmount { get; set; }
        public Nullable<decimal> Suku_Bunga { get; set; }
        public Nullable<int> termInWeeks { get; set; }
        public Nullable<int> cycle { get; set; }
        public Nullable<int> gracePeriodInWeeks { get; set; }
        public Nullable<System.DateTime> disbursementDate { get; set; }
        public Nullable<System.DateTime> dueDate { get; set; }
        public Nullable<int> termDurationInWeeks { get; set; }
        public Nullable<System.DateTime> termStart { get; set; }
        public Nullable<System.DateTime> termEnd { get; set; }
        public Nullable<double> ageAtTermStart { get; set; }
        public Nullable<double> ageAtTermEnd { get; set; }
        public string contract { get; set; }
        public Nullable<double> premiumAmount { get; set; }
        public Nullable<double> brokerageFeeAmount { get; set; }
        public string coverNoteNumber { get; set; }
        public string regno_batch { get; set; }
    }
}
