//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPMIntegration
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_placing_batch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_placing_batch()
        {
            this.tbl_participant_list = new HashSet<tbl_participant_list>();
        }
    
        public Nullable<int> batch_status { get; set; }
        public Nullable<System.DateTime> insert_date { get; set; }
        public Nullable<System.DateTime> process_date { get; set; }
        public string id { get; set; }
        public Nullable<System.DateTime> createdTime { get; set; }
        public string status { get; set; }
        public Nullable<int> totalInsurables { get; set; }
        public Nullable<int> totalCoveredInsurables { get; set; }
        public Nullable<int> totalRejectedInsurables { get; set; }
        public Nullable<int> totalUncoveredInsurables { get; set; }
        public Nullable<int> totalCoveredInsurablesUnderPolicy { get; set; }
        public Nullable<int> totalCoveredInsurablesNotUnderPolicy { get; set; }
        public int gen_id { get; set; }
    
        public virtual tbl_batch_status tbl_batch_status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_participant_list> tbl_participant_list { get; set; }
    }
}
